--- # Build host Ansible Playbook
- hosts: builder
  gather_facts: yes
  vars:
    bashrc_host_type: KVM
  vars_files:
    - vars/defaults.yml
    - vars/telegraf.yml
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/telegraf.yml