--- # Dev host Ansible Playbook
- hosts: dev
  gather_facts: yes
  vars:
    bashrc_host_type: KVM
  vars_files:
    - vars/defaults.yml
    - vars/telegraf.yml
  roles:
     - { role: rossmcdonald.telegraf }
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/dev.yml
    - include: tasks/nginx.yml