--- # Observer Ansible Playbook
- hosts: observer
  gather_facts: yes
  vars:
    bashrc_host_type: KVM
    prometheus_components:
      - prometheus

  vars_files:
    - vars/defaults.yml
    - vars/telegraf.yml
    - vars/influx.yml
    - vars/prometheus.yml
    #- vars/grafana.yml
  roles:
     - { role: rossmcdonald.telegraf }
     - { role: rossmcdonald.influxdb }  
     #- { role: william-yeh.prometheus }
  
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/meshping.yml
    - include: tasks/prometheus.yml
    - include: tasks/grafana.yml

    #- include: tasks/grafana.yml
# sudo grafana-cli plugins install grafana-clock-panel
# sudo grafana-cli plugins install natel-discrete-panel
# sudo grafana-cli plugins install briangann-gauge-panel
# sudo grafana-cli plugins install vonage-status-panel
# sudo grafana-cli plugins install neocat-cal-heatmap-panel
# #sudo grafana-cli plugins install natel-plotly-panel

    # Prometheus server to poll all our instances

    # - name: create influxDB data mount point
    #   file:
    #     name: "{{ influxdb_data_dir }}"
    #     state: directory

    # - name: mount influxDB NFS share
    #   mount:
    #     name: "{{ influx_data_dir }}"
    #     src: "{{ nfs_share }}"
    #     fstype: nfs
    #     state: mounted
    #     opts: "username={{ cifs_username }},password={{ cifs_password }}"