--- # Observer Ansible Playbook
- hosts: observer
  gather_facts: yes
  vars:
    bashrc_host_type: KVM
  vars_files:
    - vars/defaults.yml
    - vars/telegraf.yml
    - vars/influx.yml
    #- vars/prometheus.yml
    #- vars/grafana.yml
  roles:
     - { role: rossmcdonald.telegraf }
     - { role: rossmcdonald.influxdb }  
     - { role: williamyeh.prometheus }
  
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/meshping.yml
    #- include: tasks/influx.yml
    #- include: tasks/grafana.yml
    # Prometheus server to poll all our instances
    #- include: tasks/prometheus_server.yml
    # Exporter for meshping
    #- include: tasks/prometheus_explorer.yml

    # - name: create influxDB data mount point
    #   file:
    #     name: "{{ influxdb_data_dir }}"
    #     state: directory

    # - name: mount influxDB NFS share
    #   mount:
    #     name: "{{ influx_data_dir }}"
    #     src: "{{ nfs_share }}"
    #     fstype: nfs
    #     state: mounted
    #     opts: "username={{ cifs_username }},password={{ cifs_password }}"