--- # Sickrage Ansible Playbook
- hosts: sickrage
  gather_facts: yes
  vars:
    bashrc_host_type: KVM
  vars_files:
    - vars/defaults.yml
    - vars/telegraf.yml
     
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/telegraf.yml
    - include: tasks/sickrage.yml
    - include: tasks/rclone.yml
    - include: tasks/backups.yml
    
      #- debug: var=result

      #notify: Restart sickrage service

  handlers:
      #- name: Restart sickrage service
      #action: service name=sickrage start=restarted
