--- # Transmission Ansible playbook
- hosts: transmission
  gather_facts: yes
  vars:
    bashrc_host_type: AWS
    prometheus_components:
      - node_exporter
  vars_files:
    - vars/defaults.yml
    - vars/prometheus.yml     
  tasks:
    - include: tasks/bashrc.yml
    - include: tasks/base.yml
    - include: tasks/prometheus.yml