--- # Base tasks to be done across all VM's
- name: Disable SELinux
  selinux:
    state: disabled
  when:
    - ansible_distribution | regex_search('(CentOS)')
    
- name: Ensure CentOS specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - iftop
    - vim
    - git
    - fuse
    - bc
    - wget
    - telnet
    - curl
    - mlocate
    - epel-release
  register: result
  when:
    - ansible_distribution | regex_search('(CentOS)')

- name: Ensure Ubuntu specific packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - iftop
    - vim
    - git
    - fuse
    - bc
    - wget
    - telnet
    - curl
    - mlocate
    - snap
    - lm-sensors
    - hddtemp
    - python-httplib2
    - python-apt
    - apt-transport-https
  register: result
  when:
    - ansible_distribution | regex_search('(Ubuntu)')

- name: Ensure Debian specific packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - iftop
    - vim
    - git
    - fuse
    - bc
    - wget
    - telnet
    - curl
    - python-httplib2
    - python-apt
    - apt-transport-https
  register: result
  when:
    - ansible_distribution | regex_search('(Debian)')

- name: Ensure scripts directory
  file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Check /etc/hosts before running next task
  shell: RESULT=$(grep -c 127.0.1.1 /etc/hosts); if [ $RESULT != 0 ]; then echo 'true'; else echo 'false'; fi
  register: grep_output

- name: Ensure host can resolve itself
  shell: echo 127.0.1.1 $(hostname) >> /etc/hosts
  when: grep_output.stdout.find("false") == 0