--- # Base tasks to be done across all VM's
- name: Ensure CentOS specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - iftop
    - vim
    - git
    - fuse
    - epel-release
  register: result
  when:
    - ansible_distribution == 'CentOS'

- name: Ensure Ubuntu specific packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - iftop
    - vim
    - git
    - fuse
    - snap
  register: result
  when:
    - ansible_distribution | regex_search('(Ubuntu)')

- name: Ensure scripts directory
  file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes