--- # Base tasks to be done across all VM's
- name: Ensure packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iftop
    - vim
    - epel-release
    - git
    - fuse
  register: result

- name: Ensure scripts directory
  file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes