--- # Base bashrc setup for fun
- name: Set correct Bash config location
  bash_config: '/etc/bashrc'
  when:
    - ansible_distribution == 'CentOS'

- name: Set correct Bash config location
  bash_config: '/etc/bash.bashrc'
  when:
    - ansible_distribution | regex_search('(Debian|Ubuntu)')


- name: Setup bashrc
  blockinfile:
    dest: "{{ bash_config }}"
    block: |
      # Color stuff
      USER_COLOR="\e[92m"
      HOST_COLOR="\e[93m"
      HEADER_COLOR="\e[38;5;39m"
      NO_COLOR="\e[39m"
      
      if [ ${UID} -eq 0 ]; then
        USER_COLOR="\e[91m"
      fi
      
      PS1="${HEADER_COLOR}{{ bashrc_host_type }} ${USER_COLOR}\u${HOST_COLOR}@\h \W \\$ ${NO_COLOR}"
