--- # Grafana Setup
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ grafana_rpm_url }}"
  register: result

- name: Enable grafana service
  systemd:
    daemon_reload: yes
    name: grafana-server
    enabled: yes
    state: started

- name: Install grafana plugins
  command: "{{ item }}"
  with_items:
    - grafana-cli plugins install grafana-piechart-panel
    - grafana-cli plugins install grafana-clock-panel
    - grafana-cli plugins install natel-discrete-panel
    - grafana-cli plugins install briangann-gauge-panel
    - grafana-cli plugins install vonage-status-panel
    - grafana-cli plugins install neocat-cal-heatmap-panel
    - grafana-cli plugins install natel-plotly-panel