--- #HAProxy installer
- name: Ensure necessary packages are installed (CentOS)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
  register: result
  when:
    - ansible_distribution == 'CentOS'

- name: Ensure necessary packages are installed (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
  register: result
  when:
    - ansible_distribution | regex_search('(Debian|Ubuntu)')

- name: Setup haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    force: yes
    backup: yes

- name: Enable haproxy service
  systemd:
    daemon_reload: yes
    name: haproxy
    enabled: yes
    state: restarted