--- # Meshping Ansible Tasks
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mercurial
    - Cython
    - liboping-devel
    - liboping
    - python-flask
    - python-redis
    - python-devel
    - redis
    - gcc

- name: Checkout meshping Bitbucket project
  hg:
    repo: http://bitbucket.org/Svedrin/meshping
    dest: /opt/meshping

- name: Build meshping
  command: chdir=/opt/meshping ./build.sh
  register: result

- name: Create cli symlink
  file:
    src: /opt/meshping/cli.py
    dest: /usr/bin/mpcli
    state: link

- name: Ensure meshping.service file
  file:
    path: /etc/systemd/system/meshping.service
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Manage meshping.service content
  blockinfile:
    dest: /etc/systemd/system/meshping.service
    block: |
      [Unit]
      Description=meshping
      After=network.target remote-fs.target nss-lookup.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/python -- /opt/meshping/src/meshping.py

      [Install]
      WantedBy=multi-user.target

- name: Enable redis service
  systemd:
    daemon_reload: no
    name: redis
    enabled: yes
    state: started

- name: Enable meshping service
  systemd:
    daemon_reload: yes
    name: meshping
    enabled: yes
    state: started

- name: Setup ping targets
  command: "{{ item }}"
  with_items:
    - mpcli -a google.com@8.8.8.8
    - mpcli -a router@192.168.0.1
    - mpcli -a eu.battle.net@185.60.115.40
    - mpcli -a speedtest-lon1.digitalocean.com@46.101.44.214
    - mpcli -a speedtest-nyc1.digitalocean.com@165.227.194.167
    - mpcli -a speedtest-sfo1.digitalocean.com@107.170.223.15
    - mpcli -a speedtest.mybroadband.co.za@196.10.98.18